site :opscode
cookbook 'yum'
#cookbook 'chef-rvm', git: 'https://github.com/fnichol/chef-rvm.git'
cookbook 'rbenv', :git => 'https://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
cookbook 'ruby_build'

#The following cookbooks configure Rails Environment.
cookbook 'nginx', '>=1.7.0'
cookbook 'runit'
